CREATE SEQUENCE SEQ_MEMBRO;
CREATE SEQUENCE SEQ_TIME;

CREATE TABLE TIME(
ID             	NUMBER(5) CONSTRAINT TIME_ID_PK PRIMARY KEY,
NOME          	VARCHAR2(50) CONSTRAINT TIME_NOME_NN NOT NULL,
LIGA		VARCHAR2(15) CONSTRAINT TIME_LIGA_NN NOT NULL,
CONSTRAINT TIME_UN UNIQUE(NOME) NOT NULL);

CREATE TABLE MEMBRO(
ID             NUMBER(5) CONSTRAINT MEMBRO_ID_PK PRIMARY KEY,
NOME          	VARCHAR2(50) CONSTRAINT MEMBRO_NOME_NN NOT NULL,
POSICAO	VARCHAR2(15) CONSTRAINT MEMBRO_POSICAO_NN NOT NULL,
DATA_ADIMISSAO DATE CONSTRAINT MEMBRO_DATA_ADIMISSAO_NN NOT NULL,
TIME_ID 	NUMBER(5) CONSTRAINT MEMBRO_TIME_FK REFERENCES TIME(ID) CONSTRAINT MEMBRO_TIME_ID_NN NOT NULL,
CONSTRAINT MEMBRO_UN UNIQUE(NOME) NOT NULL);